import type { Metadata } from "next";
import Nav from "@/components/Nav";
import Footer from "@/components/Footer";
import JsonLd from "@/components/JsonLd";
import { Link } from "@/i18n/navigation";
import { routing } from "@/i18n/routing";

type Props = { params: Promise<{ locale: string }> };
type Copy = {
  seoTitle: string; title: string; description: string; eyebrow: string; home: string; breadcrumb: string;
  quote: string; guide: string; scopeTitle: string; scopeIntro: string; scope: Array<{title:string;body:string}>;
  processTitle: string; process: Array<{title:string;body:string}>; detailsTitle: string; detailsBody: string; details: string[];
  cautionTitle: string; cautionBody: string; officialLink: string; faqTitle: string; faqs: Array<{question:string;answer:string}>;
  finalTitle: string; finalBody: string;
};

const COPY: Record<string, Copy> = {
  en: {
    seoTitle: "Customs Clearance Vietnam | Import & Export Support", title: "Customs clearance support in Vietnam built around accurate shipment data",
    description: "Prepare import or export customs information, documents and coordination in Vietnam without relying on fixed duty or clearance promises.", eyebrow: "Vietnam import and export coordination", home: "Home", breadcrumb: "Customs Clearance Vietnam",
    quote: "Request customs support", guide: "See the preparation process", scopeTitle: "What customs coordination can cover", scopeIntro: "The applicable procedure depends on the commodity, HS classification, trade direction, trader, origin, value and current controls.",
    scope: [{title:"Document readiness",body:"Review the commercial invoice, packing list, transport document and supporting records available for the shipment."},{title:"HS and policy checks",body:"Confirm the proposed HS code and identify whether current licensing or specialized inspection requirements may apply."},{title:"Declaration coordination",body:"Align shipment data with the party legally responsible for the customs declaration and supporting documents."},{title:"Release and delivery planning",body:"Coordinate operational milestones after the competent authority completes the applicable process."}],
    processTitle: "A careful preparation process", process: [{title:"Identify the transaction",body:"Confirm import or export, trader, Incoterm, commodity, origin, value and route."},{title:"Check current requirements",body:"Review the current procedure, policy controls and document requirements for the specific goods."},{title:"Reconcile documents",body:"Check that descriptions, quantities, weights, values and parties are consistent across records."},{title:"Coordinate filing",body:"Work with the authorized declarant and respond to requests from the competent authority."}],
    detailsTitle: "Information needed before customs review", detailsBody: "Accurate information reduces avoidable corrections but does not guarantee a particular customs outcome.", details:["Importer or exporter legal entity and tax details","Commercial invoice and packing list","Commodity description, intended use and proposed HS code","Country of origin and supporting origin documents if relevant","Transport document and shipment route","Incoterm, customs value basis and currency","Licences, certificates or specialized inspection records when applicable"],
    cautionTitle:"Important: requirements are shipment-specific", cautionBody:"Duties, taxes, licences, inspection and release decisions depend on current law and the competent authorities. Verify the latest requirements for the actual commodity before shipping.", officialLink:"Check the Viet Nam National Trade Repository", faqTitle:"Vietnam customs questions",
    faqs:[{question:"Can duty and tax be confirmed from a product name alone?",answer:"No. Classification, origin, value, trade program and current rules must be reviewed for the actual goods."},{question:"Are all shipments subject to the same documents?",answer:"No. The required file varies by import or export procedure, commodity controls and the transaction."},{question:"Can specialized inspection or a licence apply?",answer:"Yes, for certain goods. This should be checked before cargo moves."},{question:"Does document preparation guarantee release?",answer:"No. The competent authority makes the applicable inspection and release decisions."}],
    finalTitle:"Preparing an import or export shipment in Vietnam?", finalBody:"Share the real commodity, parties, route and available documents for a shipment-specific review."
  },
  vi: {
    seoTitle:"Thông quan Việt Nam | Hỗ trợ xuất nhập khẩu", title:"Hỗ trợ thông quan tại Việt Nam dựa trên dữ liệu chính xác của lô hàng", description:"Chuẩn bị thông tin, chứng từ và phối hợp thủ tục xuất nhập khẩu tại Việt Nam, không cam kết cố định về thuế hoặc kết quả thông quan.", eyebrow:"Phối hợp xuất nhập khẩu tại Việt Nam", home:"Trang chủ", breadcrumb:"Thông quan Việt Nam", quote:"Yêu cầu hỗ trợ hải quan", guide:"Xem quy trình chuẩn bị", scopeTitle:"Phạm vi phối hợp hải quan", scopeIntro:"Thủ tục áp dụng phụ thuộc mặt hàng, mã HS, chiều xuất nhập, chủ thể, xuất xứ, trị giá và chính sách hiện hành.",
    scope:[{title:"Chuẩn bị chứng từ",body:"Rà hóa đơn thương mại, packing list, chứng từ vận tải và hồ sơ hỗ trợ hiện có."},{title:"Kiểm tra HS và chính sách",body:"Xác nhận mã HS dự kiến và kiểm tra giấy phép hoặc kiểm tra chuyên ngành có thể áp dụng."},{title:"Phối hợp khai báo",body:"Đồng bộ dữ liệu với bên có trách nhiệm pháp lý khai hải quan và cung cấp hồ sơ."},{title:"Kế hoạch giải phóng hàng",body:"Phối hợp các mốc khai thác sau khi cơ quan có thẩm quyền hoàn tất thủ tục áp dụng."}],
    processTitle:"Quy trình chuẩn bị cẩn trọng", process:[{title:"Xác định giao dịch",body:"Làm rõ xuất hay nhập, chủ thể, Incoterm, mặt hàng, xuất xứ, trị giá và tuyến."},{title:"Kiểm tra yêu cầu hiện hành",body:"Rà thủ tục, chính sách quản lý và chứng từ cho đúng mặt hàng."},{title:"Đối chiếu chứng từ",body:"Kiểm tra mô tả, số lượng, trọng lượng, trị giá và các bên thống nhất giữa hồ sơ."},{title:"Phối hợp khai",body:"Làm việc với người khai được ủy quyền và phản hồi yêu cầu của cơ quan có thẩm quyền."}],
    detailsTitle:"Thông tin cần có trước khi kiểm tra hải quan", detailsBody:"Thông tin chính xác giúp giảm sửa đổi không cần thiết nhưng không bảo đảm một kết quả thông quan cụ thể.", details:["Pháp nhân xuất khẩu hoặc nhập khẩu và thông tin thuế","Hóa đơn thương mại và packing list","Mô tả hàng, công dụng và mã HS dự kiến","Nước xuất xứ và chứng từ xuất xứ nếu liên quan","Chứng từ vận tải và tuyến đi","Incoterm, cơ sở trị giá và đồng tiền","Giấy phép, chứng nhận hoặc hồ sơ kiểm tra chuyên ngành nếu áp dụng"],
    cautionTitle:"Lưu ý: yêu cầu phụ thuộc từng lô hàng", cautionBody:"Thuế, giấy phép, kiểm tra và quyết định giải phóng hàng phụ thuộc quy định hiện hành và cơ quan có thẩm quyền. Cần xác minh yêu cầu mới nhất cho đúng mặt hàng trước khi gửi.", officialLink:"Tra cứu Cổng Thông tin Thương mại Việt Nam", faqTitle:"Câu hỏi về hải quan Việt Nam",
    faqs:[{question:"Chỉ có tên hàng thì xác định được thuế không?",answer:"Không. Cần xem phân loại, xuất xứ, trị giá, chương trình thương mại và quy định hiện hành."},{question:"Mọi lô hàng dùng cùng một bộ chứng từ không?",answer:"Không. Hồ sơ thay đổi theo thủ tục, chính sách mặt hàng và giao dịch."},{question:"Có thể cần giấy phép hoặc kiểm tra chuyên ngành không?",answer:"Có, với một số mặt hàng và cần kiểm tra trước khi hàng đi."},{question:"Chuẩn bị đủ chứng từ có bảo đảm thông quan không?",answer:"Không. Cơ quan có thẩm quyền quyết định việc kiểm tra và giải phóng hàng."}], finalTitle:"Bạn đang chuẩn bị lô hàng xuất hoặc nhập tại Việt Nam?", finalBody:"Gửi thông tin thật về mặt hàng, các bên, tuyến và chứng từ để rà theo từng lô hàng."
  },
  it: {
    seoTitle:"Sdoganamento Vietnam | Supporto import export",title:"Supporto doganale in Vietnam basato su dati accurati",description:"Prepara informazioni, documenti e coordinamento import-export in Vietnam senza promesse fisse su dazi o svincolo.",eyebrow:"Coordinamento import export Vietnam",home:"Home",breadcrumb:"Sdoganamento Vietnam",quote:"Richiedi supporto doganale",guide:"Vedi il processo",scopeTitle:"Cosa può includere il coordinamento",scopeIntro:"La procedura dipende da merce, codice HS, direzione, operatore, origine, valore e controlli vigenti.",scope:[{title:"Documenti",body:"Verifica fattura, packing list, documento di trasporto e supporti disponibili."},{title:"HS e controlli",body:"Controlla codice proposto, licenze e ispezioni eventualmente applicabili."},{title:"Dichiarazione",body:"Allinea i dati con il soggetto legalmente responsabile della dichiarazione."},{title:"Svincolo e consegna",body:"Coordina le fasi operative dopo il processo dell'autorità competente."}],processTitle:"Preparazione prudente",process:[{title:"Definisci operazione",body:"Import/export, operatore, Incoterm, merce, origine, valore e rotta."},{title:"Verifica requisiti",body:"Controlla procedura e documenti vigenti."},{title:"Riconcilia dati",body:"Allinea descrizioni, quantità, pesi, valori e parti."},{title:"Coordina deposito",body:"Collabora con il dichiarante autorizzato e l'autorità."}],detailsTitle:"Dati necessari",detailsBody:"Dati accurati riducono correzioni ma non garantiscono lo svincolo.",details:["Operatore e dati fiscali","Fattura e packing list","Descrizione, uso e codice HS proposto","Origine e prove pertinenti","Documento di trasporto e rotta","Incoterm, valore e valuta","Licenze o certificati applicabili"],cautionTitle:"I requisiti dipendono dalla spedizione",cautionBody:"Dazi, imposte, licenze, controlli e svincolo dipendono dalle norme vigenti e dalle autorità. Verifica prima della spedizione.",officialLink:"Consulta il Viet Nam National Trade Repository",faqTitle:"Domande doganali",faqs:[{question:"Basta il nome prodotto per definire i dazi?",answer:"No. Servono classificazione, origine, valore e regole vigenti."},{question:"I documenti sono uguali per tutti?",answer:"No. Dipendono da procedura, merce e transazione."},{question:"Può servire una licenza?",answer:"Sì, per alcune merci; verifica prima della partenza."},{question:"I documenti garantiscono lo svincolo?",answer:"No. Decide l'autorità competente."}],finalTitle:"Prepari un'importazione o esportazione in Vietnam?",finalBody:"Invia merce, parti, rotta e documenti per una verifica specifica."
  },
  es: {
    seoTitle:"Despacho aduanero Vietnam | Importación y exportación",title:"Apoyo aduanero en Vietnam basado en datos precisos",description:"Prepara información, documentos y coordinación de importación o exportación en Vietnam sin promesas fijas de impuestos o despacho.",eyebrow:"Coordinación de comercio exterior en Vietnam",home:"Inicio",breadcrumb:"Despacho aduanero Vietnam",quote:"Solicitar apoyo aduanero",guide:"Ver el proceso",scopeTitle:"Qué puede cubrir la coordinación",scopeIntro:"El procedimiento depende de mercancía, HS, dirección, operador, origen, valor y controles vigentes.",scope:[{title:"Documentación",body:"Revisa factura, packing list, transporte y soportes disponibles."},{title:"HS y controles",body:"Comprueba código propuesto, licencias e inspecciones aplicables."},{title:"Declaración",body:"Coordina datos con la parte legalmente responsable."},{title:"Levante y entrega",body:"Coordina hitos después del proceso de la autoridad competente."}],processTitle:"Preparación cuidadosa",process:[{title:"Definir operación",body:"Importación/exportación, operador, Incoterm, mercancía, origen, valor y ruta."},{title:"Revisar requisitos",body:"Comprueba procedimiento y documentos actuales."},{title:"Conciliar datos",body:"Alinea descripción, cantidades, pesos, valores y partes."},{title:"Coordinar presentación",body:"Trabaja con el declarante autorizado y la autoridad."}],detailsTitle:"Información necesaria",detailsBody:"Los datos precisos reducen correcciones pero no garantizan un resultado.",details:["Operador y datos fiscales","Factura y packing list","Descripción, uso y HS propuesto","Origen y pruebas pertinentes","Transporte y ruta","Incoterm, valor y moneda","Licencias o certificados aplicables"],cautionTitle:"Los requisitos dependen del envío",cautionBody:"Impuestos, licencias, inspección y levante dependen de normas y autoridades vigentes. Verifica antes de enviar.",officialLink:"Consultar el Viet Nam National Trade Repository",faqTitle:"Preguntas aduaneras",faqs:[{question:"¿Basta el nombre para calcular impuestos?",answer:"No. Se requiere clasificación, origen, valor y reglas vigentes."},{question:"¿Todos usan los mismos documentos?",answer:"No. Dependen del procedimiento, mercancía y operación."},{question:"¿Puede requerirse licencia?",answer:"Sí, para ciertas mercancías; debe revisarse antes."},{question:"¿Los documentos garantizan el levante?",answer:"No. Decide la autoridad competente."}],finalTitle:"¿Preparas una importación o exportación en Vietnam?",finalBody:"Comparte mercancía, partes, ruta y documentos para una revisión específica."
  },
  id: {
    seoTitle:"Customs Clearance Vietnam | Dukungan ekspor impor",title:"Dukungan bea cukai Vietnam berdasarkan data akurat",description:"Siapkan informasi, dokumen, dan koordinasi ekspor-impor di Vietnam tanpa janji tetap mengenai pajak atau clearance.",eyebrow:"Koordinasi ekspor impor Vietnam",home:"Beranda",breadcrumb:"Customs Clearance Vietnam",quote:"Minta dukungan bea cukai",guide:"Lihat proses",scopeTitle:"Cakupan koordinasi",scopeIntro:"Prosedur bergantung pada komoditas, HS, arah perdagangan, pelaku, asal, nilai, dan kontrol saat ini.",scope:[{title:"Kesiapan dokumen",body:"Tinjau invoice, packing list, dokumen transportasi, dan pendukung."},{title:"HS dan kebijakan",body:"Periksa kode, izin, dan inspeksi yang mungkin berlaku."},{title:"Koordinasi deklarasi",body:"Selaraskan data dengan pihak yang bertanggung jawab secara hukum."},{title:"Release dan delivery",body:"Koordinasikan tahapan setelah proses otoritas terkait."}],processTitle:"Proses persiapan",process:[{title:"Kenali transaksi",body:"Impor/ekspor, pelaku, Incoterm, komoditas, asal, nilai, dan rute."},{title:"Periksa persyaratan",body:"Tinjau prosedur dan dokumen terkini."},{title:"Cocokkan data",body:"Selaraskan deskripsi, jumlah, berat, nilai, dan pihak."},{title:"Koordinasi pengajuan",body:"Bekerja dengan deklarant berwenang dan otoritas."}],detailsTitle:"Informasi yang diperlukan",detailsBody:"Data akurat mengurangi koreksi tetapi tidak menjamin hasil clearance.",details:["Pelaku dan data pajak","Invoice dan packing list","Deskripsi, penggunaan, dan HS usulan","Asal dan bukti terkait","Dokumen transportasi dan rute","Incoterm, nilai, dan mata uang","Izin atau sertifikat yang berlaku"],cautionTitle:"Persyaratan khusus tiap kiriman",cautionBody:"Pajak, izin, inspeksi, dan release bergantung pada aturan dan otoritas saat ini. Verifikasi sebelum pengiriman.",officialLink:"Periksa Viet Nam National Trade Repository",faqTitle:"Pertanyaan bea cukai",faqs:[{question:"Apakah nama produk cukup untuk menentukan pajak?",answer:"Tidak. Perlu klasifikasi, asal, nilai, dan aturan saat ini."},{question:"Apakah semua kiriman memakai dokumen sama?",answer:"Tidak. Bergantung pada prosedur, barang, dan transaksi."},{question:"Apakah izin mungkin diperlukan?",answer:"Ya, untuk barang tertentu; periksa sebelum dikirim."},{question:"Apakah dokumen menjamin release?",answer:"Tidak. Otoritas yang berwenang memutuskan."}],finalTitle:"Menyiapkan impor atau ekspor di Vietnam?",finalBody:"Bagikan komoditas, pihak, rute, dan dokumen untuk tinjauan khusus."
  }
};

const BASE_URL="https://www.bookingbyjohnly.com";
export function generateStaticParams(){return routing.locales.map(locale=>({locale}));}
export async function generateMetadata({params}:Props):Promise<Metadata>{const{locale}=await params;const c=COPY[locale]||COPY.en;const path=`/${locale}/services/customs-clearance-vietnam`;return{title:c.seoTitle,description:c.description,alternates:{canonical:path,languages:{...Object.fromEntries(routing.locales.map(l=>[l,`/${l}/services/customs-clearance-vietnam`])),"x-default":"/en/services/customs-clearance-vietnam"}},openGraph:{title:c.seoTitle,description:c.description,type:"website",url:path},twitter:{card:"summary_large_image",title:c.seoTitle,description:c.description}};}

export default async function CustomsPage({params}:Props){const{locale}=await params;const c=COPY[locale]||COPY.en;const url=`${BASE_URL}/${locale}/services/customs-clearance-vietnam`;const service={"@context":"https://schema.org","@type":"Service",name:c.title,description:c.description,url,serviceType:"Customs clearance coordination",areaServed:{"@type":"Country",name:"Vietnam"},provider:{"@id":`${BASE_URL}/#organization`}};const faq={"@context":"https://schema.org","@type":"FAQPage",mainEntity:c.faqs.map(x=>({"@type":"Question",name:x.question,acceptedAnswer:{"@type":"Answer",text:x.answer}}))};const crumbs={"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:c.home,item:`${BASE_URL}/${locale}`},{"@type":"ListItem",position:2,name:c.breadcrumb,item:url}]};return <main className="min-h-screen bg-bg-primary text-text-primary"><JsonLd data={[service,faq,crumbs]}/><Nav/>
<section className="bg-[#0B1F3A] px-5 py-16 text-white lg:px-8 lg:py-24"><div className="mx-auto max-w-6xl"><nav aria-label="Breadcrumb" className="text-sm text-slate-300"><Link href="/">{c.home}</Link><span className="mx-2">/</span><span>{c.breadcrumb}</span></nav><p className="mt-10 text-sm font-black uppercase tracking-widest text-orange-300">{c.eyebrow}</p><h1 className="mt-4 max-w-4xl text-4xl font-black leading-tight sm:text-6xl">{c.title}</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-slate-200">{c.description}</p><div className="mt-9 flex flex-wrap gap-4"><Link href="/?mode=Customs%20Clearance&source=customs-clearance-vietnam-hero#request" className="rounded-md bg-accent-orange px-6 py-3 font-black">{c.quote}</Link><a href="#process" className="rounded-md border border-white/30 px-6 py-3 font-black">{c.guide}</a></div></div></section>
<section className="mx-auto max-w-6xl px-5 py-14 lg:px-8 lg:py-20"><h2 className="text-3xl font-black text-[#0B1F3A]">{c.scopeTitle}</h2><p className="mt-4 max-w-4xl leading-7 text-text-secondary">{c.scopeIntro}</p><div className="mt-8 grid gap-5 md:grid-cols-2">{c.scope.map(x=><article key={x.title} className="rounded-lg border border-border-subtle bg-white p-6 shadow-sm"><h3 className="text-xl font-black text-[#0B1F3A]">{x.title}</h3><p className="mt-3 leading-7 text-text-secondary">{x.body}</p></article>)}</div></section>
<section id="process" className="bg-white px-5 py-14 lg:px-8 lg:py-20"><div className="mx-auto max-w-6xl"><h2 className="text-3xl font-black text-[#0B1F3A]">{c.processTitle}</h2><ol className="mt-8 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{c.process.map((x,i)=><li key={x.title} className="rounded-lg border border-border-subtle bg-bg-primary p-6"><span className="font-black text-accent-orange">0{i+1}</span><h3 className="mt-2 text-lg font-black text-[#0B1F3A]">{x.title}</h3><p className="mt-3 leading-7 text-text-secondary">{x.body}</p></li>)}</ol></div></section>
<section className="mx-auto grid max-w-6xl gap-10 px-5 py-14 lg:grid-cols-2 lg:px-8 lg:py-20"><div><h2 className="text-3xl font-black text-[#0B1F3A]">{c.detailsTitle}</h2><p className="mt-4 leading-7 text-text-secondary">{c.detailsBody}</p><Link href="/?mode=Customs%20Clearance&source=customs-clearance-vietnam-details#request" className="mt-6 inline-flex rounded-md bg-accent-orange px-6 py-3 font-black text-white">{c.quote}</Link></div><ul className="space-y-3">{c.details.map(x=><li key={x} className="rounded-md bg-white p-4 shadow-sm">{x}</li>)}</ul></section>
<section className="bg-amber-50 px-5 py-14 lg:px-8"><div className="mx-auto max-w-4xl"><h2 className="text-3xl font-black text-[#0B1F3A]">{c.cautionTitle}</h2><p className="mt-4 leading-7 text-text-secondary">{c.cautionBody}</p><a href="https://vntr.moit.gov.vn/procedures" target="_blank" rel="noreferrer" className="mt-5 inline-flex font-black text-ocean-blue underline underline-offset-4">{c.officialLink} ↗</a></div></section>
<section className="bg-white px-5 py-14 lg:px-8 lg:py-20"><div className="mx-auto max-w-4xl"><h2 className="text-3xl font-black text-[#0B1F3A]">{c.faqTitle}</h2><div className="mt-8 space-y-4">{c.faqs.map(x=><article key={x.question} className="rounded-lg border border-border-subtle p-6"><h3 className="text-lg font-black text-[#0B1F3A]">{x.question}</h3><p className="mt-3 leading-7 text-text-secondary">{x.answer}</p></article>)}</div></div></section>
<section className="bg-[#0B1F3A] px-5 py-14 text-center text-white"><h2 className="text-3xl font-black">{c.finalTitle}</h2><p className="mx-auto mt-4 max-w-2xl leading-7 text-slate-200">{c.finalBody}</p><Link href="/?mode=Customs%20Clearance&source=customs-clearance-vietnam-final#request" className="mt-8 inline-flex rounded-md bg-accent-orange px-6 py-3 font-black">{c.quote}</Link></section><Footer/></main>}
